name: Publicação Go após integração

on:
  push:
    branches: [master]

jobs:
  go-ci:
    uses: ./.github/workflows/go-ci.yml

  publish:
    needs: go-ci
    permissions:
      contents: write
      pull-requests: read
      issues: read
    uses: ModulosTestesAutomatizados/.github/.github/workflows/version-publish.yml@8b0c6a372ab560400a735bbe42a8a39af823cacf
    with:
      adapter: go-gitsemver
      project_path: examples/go-gitsemver
      release_branch: release/v1.0.1
      target_branch: master
      homologation_environment: homologation
